import { Repository, DataSource } from 'typeorm';
import { Injectable } from '@nestjs/common';
import {
  HighlightEntity,
  HighlightStatus,
  HighlightType,
  HighlightSource,
  StreamSessionEntity,
  MatchEntity,
  TournamentEntity,
  UserEntity,
} from '../database/entities';
import { NotFoundError, ValidationError } from './errors';
import { CacheService } from './cache.service';
import { NotificationService } from './notification.service';

export interface CreateHighlightInput {
  streamSessionId: string;
  matchId?: string;
  tournamentId?: string;
  playerId?: string;
  createdBy: string;
  type: HighlightType;
  source: HighlightSource;
  title: string;
  description?: string;
  startTime: number;
  endTime: number;
  metadata?: {
    platform?: string;
    platformClipId?: string;
    tags?: string[];
    language?: string;
    region?: string;
    featured?: boolean;
    priority?: number;
    autoGenerated?: boolean;
  };
  aiMetadata?: {
    confidence: number;
    detectedEvents: Array<{
      event: string;
      timestamp: number;
      confidence: number;
      metadata?: Record<string, any>;
    }>;
    tags: string[];
    sentiment?: 'positive' | 'negative' | 'neutral';
    excitement?: number;
  };
  region?: string;
}

export interface UpdateHighlightInput {
  title?: string;
  description?: string;
  metadata?: Record<string, any>;
  aiMetadata?: Record<string, any>;
  expiresAt?: Date;
}

export interface HighlightQueryOptions {
  streamSessionId?: string;
  matchId?: string;
  tournamentId?: string;
  playerId?: string;
  createdBy?: string;
  status?: HighlightStatus;
  type?: HighlightType;
  source?: HighlightSource;
  region?: string;
  limit?: number;
  offset?: number;
  sortBy?: 'createdAt' | 'duration' | 'views' | 'likes' | 'engagement';
  sortOrder?: 'asc' | 'desc';
}

@Injectable()
export class HighlightService {
  constructor(
    private readonly highlightRepo: Repository<HighlightEntity>,
    private readonly streamSessionRepo: Repository<StreamSessionEntity>,
    private readonly matchRepo: Repository<MatchEntity>,
    private readonly tournamentRepo: Repository<TournamentEntity>,
    private readonly userRepo: Repository<UserEntity>,
    private readonly dataSource: DataSource,
    private readonly cacheService: CacheService,
    private readonly notificationService: NotificationService,
  ) {}

  async create(input: CreateHighlightInput): Promise<HighlightEntity> {
    // Validate stream session exists
    const streamSession = await this.streamSessionRepo.findOne({ 
      where: { id: input.streamSessionId } 
    });
    if (!streamSession) {
      throw new NotFoundError('Stream session', input.streamSessionId);
    }

    // Validate creator exists
    const creator = await this.userRepo.findOne({ 
      where: { id: input.createdBy } 
    });
    if (!creator) {
      throw new NotFoundError('Creator', input.createdBy);
    }

    // Validate match if provided
    if (input.matchId) {
      const match = await this.matchRepo.findOne({ 
        where: { id: input.matchId } 
      });
      if (!match) {
        throw new NotFoundError('Match', input.matchId);
      }
    }

    // Validate tournament if provided
    if (input.tournamentId) {
      const tournament = await this.tournamentRepo.findOne({ 
        where: { id: input.tournamentId } 
      });
      if (!tournament) {
        throw new NotFoundError('Tournament', input.tournamentId);
      }
    }

    // Validate player if provided
    if (input.playerId) {
      const player = await this.userRepo.findOne({ 
        where: { id: input.playerId } 
      });
      if (!player) {
        throw new NotFoundError('User', input.playerId);
      }
    }

    // Validate time range
    const duration = input.endTime - input.startTime;
    if (duration <= 0) {
      throw new ValidationError('End time must be after start time');
    }
    if (duration > 300) { // 5 minutes max
      throw new ValidationError('Highlight duration cannot exceed 5 minutes');
    }

    const highlight = this.highlightRepo.create({
      ...input,
      duration,
      status: HighlightStatus.PROCESSING,
      metadata: {
        platform: input.metadata?.platform || 'custom',
        platformClipId: input.metadata?.platformClipId,
        tags: input.metadata?.tags || [],
        language: input.metadata?.language,
        region: input.metadata?.region,
        featured: input.metadata?.featured ?? false,
        priority: input.metadata?.priority || 0,
        autoGenerated: input.metadata?.autoGenerated ?? true,
      },
      aiMetadata: {
        confidence: input.aiMetadata?.confidence || 0.5,
        detectedEvents: input.aiMetadata?.detectedEvents || [],
        tags: input.aiMetadata?.tags || [],
        sentiment: input.aiMetadata?.sentiment,
        excitement: input.aiMetadata?.excitement,
      },
      engagement: {
        views: 0,
        likes: 0,
        shares: 0,
        downloads: 0,
        comments: 0,
        watchTime: 0,
      },
      processingMetadata: {
        processingSteps: [
          {
            step: 'initialization',
            startedAt: new Date(),
            completedAt: new Date(),
            status: 'completed',
          },
          {
            step: 'video_processing',
            startedAt: new Date(),
            status: 'processing',
          },
        ],
        retryCount: 0,
      },
      region: input.region || 'global',
    });

    const savedHighlight = await this.highlightRepo.save(highlight);

    // Cache the highlight
    await this.cacheService.set(
      `highlight:${savedHighlight.id}`,
      savedHighlight,
      3600 // 1 hour
    );

    // Send notification to creator
    await this.notificationService.create({
      userId: input.createdBy,
      templateKey: 'highlight_created',
      channel: 'inApp',
      payload: {
        highlightId: savedHighlight.id,
        title: savedHighlight.title,
        type: savedHighlight.type,
        source: savedHighlight.source,
        duration: savedHighlight.duration,
      },
    });

    return savedHighlight;
  }

  async findById(id: string): Promise<HighlightEntity | null> {
    // Try cache first
    const cached = await this.cacheService.get<HighlightEntity>(
      `highlight:${id}`
    );
    if (cached) {
      return cached;
    }

    const highlight = await this.highlightRepo.findOne({
      where: { id },
      relations: ['streamSession', 'match', 'tournament', 'player', 'creator'],
    });

    if (highlight) {
      await this.cacheService.set(`highlight:${id}`, highlight, 3600);
    }

    return highlight;
  }

  async update(
    id: string,
    input: UpdateHighlightInput
  ): Promise<HighlightEntity> {
    const highlight = await this.findById(id);
    if (!highlight) {
      throw new NotFoundError('Highlight', id);
    }

    // Don't allow updates if highlight is being processed
    if (highlight.status === HighlightStatus.PROCESSING) {
      throw new ValidationError('Cannot update highlight while processing');
    }

    Object.assign(highlight, input);

    const updatedHighlight = await this.highlightRepo.save(highlight);

    // Update cache
    await this.cacheService.set(
      `highlight:${id}`,
      updatedHighlight,
      3600
    );

    return updatedHighlight;
  }

  async completeProcessing(
    id: string,
    videoData: {
      videoUrl: string;
      downloadUrl: string;
      thumbnailUrl?: string;
      embedUrl?: string;
      videoMetadata: {
        format: string;
        resolution: string;
        fps: number;
        bitrate: number;
        fileSize: number;
        codec?: string;
        aspectRatio?: string;
      };
    }
  ): Promise<HighlightEntity> {
    const highlight = await this.findById(id);
    if (!highlight) {
      throw new NotFoundError('Highlight', id);
    }

    if (highlight.status !== HighlightStatus.PROCESSING) {
      throw new ValidationError('Highlight is not in processing status');
    }

    highlight.status = HighlightStatus.READY;
    highlight.videoUrl = videoData.videoUrl;
    highlight.downloadUrl = videoData.downloadUrl;
    highlight.thumbnailUrl = videoData.thumbnailUrl;
    highlight.embedUrl = videoData.embedUrl;
    highlight.videoMetadata = videoData.videoMetadata;

    highlight.processingMetadata = {
      ...highlight.processingMetadata,
      processingCompletedAt: new Date(),
      processingSteps: highlight.processingMetadata.processingSteps.map(step => 
        step.status === 'processing' 
          ? { ...step, completedAt: new Date(), status: 'completed' as const }
          : step
      ),
    };

    const updatedHighlight = await this.highlightRepo.save(highlight);

    // Update cache
    await this.cacheService.set(
      `highlight:${id}`,
      updatedHighlight,
      3600
    );

    // Send notification to creator
    await this.notificationService.create({
      userId: highlight.createdBy,
      templateKey: 'highlight_ready',
      channel: 'inApp',
      payload: {
        highlightId: highlight.id,
        title: highlight.title,
        videoUrl: highlight.videoUrl,
        thumbnailUrl: highlight.thumbnailUrl,
        duration: highlight.duration,
      },
    });

    return updatedHighlight;
  }

  async approveHighlight(
    id: string,
    approvedBy: string,
    approvedAt?: Date
  ): Promise<HighlightEntity> {
    const highlight = await this.findById(id);
    if (!highlight) {
      throw new NotFoundError('Highlight', id);
    }

    if (highlight.status !== HighlightStatus.READY) {
      throw new ValidationError('Highlight must be ready before approval');
    }

    // Validate approver exists
    const approver = await this.userRepo.findOne({ 
      where: { id: approvedBy } 
    });
    if (!approver) {
      throw new NotFoundError('Approver', approvedBy);
    }

    highlight.status = HighlightStatus.APPROVED;
    highlight.approvedBy = approvedBy;
    highlight.approvedAt = approvedAt || new Date();

    const updatedHighlight = await this.highlightRepo.save(highlight);

    // Update cache
    await this.cacheService.set(
      `highlight:${id}`,
      updatedHighlight,
      3600
    );

    // Send notification to creator
    await this.notificationService.create({
      userId: highlight.createdBy,
      templateKey: 'highlight_approved',
      channel: 'inApp',
      payload: {
        highlightId: highlight.id,
        title: highlight.title,
        approvedAt: highlight.approvedAt,
      },
    });

    return updatedHighlight;
  }

  async rejectHighlight(
    id: string,
    approvedBy: string,
    rejectionReason: string
  ): Promise<HighlightEntity> {
    const highlight = await this.findById(id);
    if (!highlight) {
      throw new NotFoundError('Highlight', id);
    }

    if (highlight.status !== HighlightStatus.READY) {
      throw new ValidationError('Highlight must be ready before rejection');
    }

    // Validate approver exists
    const approver = await this.userRepo.findOne({ 
      where: { id: approvedBy } 
    });
    if (!approver) {
      throw new NotFoundError('Approver', approvedBy);
    }

    highlight.status = HighlightStatus.REJECTED;
    highlight.approvedBy = approvedBy;
    highlight.approvedAt = new Date();
    highlight.rejectionReason = rejectionReason;

    const updatedHighlight = await this.highlightRepo.save(highlight);

    // Update cache
    await this.cacheService.set(
      `highlight:${id}`,
      updatedHighlight,
      3600
    );

    // Send notification to creator
    await this.notificationService.create({
      userId: highlight.createdBy,
      templateKey: 'highlight_rejected',
      channel: 'inApp',
      payload: {
        highlightId: highlight.id,
        title: highlight.title,
        rejectionReason,
      },
    });

    return updatedHighlight;
  }

  async publishHighlight(id: string): Promise<HighlightEntity> {
    const highlight = await this.findById(id);
    if (!highlight) {
      throw new NotFoundError('Highlight', id);
    }

    if (highlight.status !== HighlightStatus.APPROVED) {
      throw new ValidationError('Highlight must be approved before publishing');
    }

    highlight.status = HighlightStatus.PUBLISHED;
    highlight.publishedAt = new Date();

    const updatedHighlight = await this.highlightRepo.save(highlight);

    // Update cache
    await this.cacheService.set(
      `highlight:${id}`,
      updatedHighlight,
      3600
    );

    // Send notification to creator
    await this.notificationService.create({
      userId: highlight.createdBy,
      templateKey: 'highlight_published',
      channel: 'inApp',
      payload: {
        highlightId: highlight.id,
        title: highlight.title,
        publishedAt: highlight.publishedAt,
      },
    });

    return updatedHighlight;
  }

  async failProcessing(id: string, errorMessage: string): Promise<HighlightEntity> {
    const highlight = await this.findById(id);
    if (!highlight) {
      throw new NotFoundError('Highlight', id);
    }

    if (highlight.status !== HighlightStatus.PROCESSING) {
      throw new ValidationError('Highlight is not in processing status');
    }

    highlight.status = HighlightStatus.FAILED;

    highlight.processingMetadata = {
      ...highlight.processingMetadata,
      processingCompletedAt: new Date(),
      processingSteps: highlight.processingMetadata.processingSteps.map(step => 
        step.status === 'processing' 
          ? { ...step, completedAt: new Date(), status: 'failed' as const, error: errorMessage }
          : step
      ),
    };

    const updatedHighlight = await this.highlightRepo.save(highlight);

    // Update cache
    await this.cacheService.set(
      `highlight:${id}`,
      updatedHighlight,
      3600
    );

    // Send notification to creator
    await this.notificationService.create({
      userId: highlight.createdBy,
      templateKey: 'highlight_processing_failed',
      channel: 'inApp',
      payload: {
        highlightId: highlight.id,
        title: highlight.title,
        errorMessage,
      },
    });

    return updatedHighlight;
  }

  async updateEngagement(
    id: string,
    engagementData: {
      views?: number;
      likes?: number;
      shares?: number;
      downloads?: number;
      comments?: number;
      watchTime?: number;
    }
  ): Promise<void> {
    const highlight = await this.findById(id);
    if (!highlight) {
      throw new NotFoundError('Highlight', id);
    }

    highlight.engagement = {
      ...highlight.engagement,
      ...engagementData,
    };

    await this.highlightRepo.save(highlight);

    // Update cache
    await this.cacheService.set(
      `highlight:${id}`,
      highlight,
      3600
    );
  }

  async findMany(options: HighlightQueryOptions): Promise<{
    highlights: HighlightEntity[];
    total: number;
  }> {
    const queryBuilder = this.highlightRepo
      .createQueryBuilder('highlight')
      .leftJoinAndSelect('highlight.streamSession', 'streamSession')
      .leftJoinAndSelect('highlight.match', 'match')
      .leftJoinAndSelect('highlight.tournament', 'tournament')
      .leftJoinAndSelect('highlight.player', 'player')
      .leftJoinAndSelect('highlight.creator', 'creator');

    if (options.streamSessionId) {
      queryBuilder.andWhere('highlight.streamSessionId = :streamSessionId', {
        streamSessionId: options.streamSessionId,
      });
    }

    if (options.matchId) {
      queryBuilder.andWhere('highlight.matchId = :matchId', {
        matchId: options.matchId,
      });
    }

    if (options.tournamentId) {
      queryBuilder.andWhere('highlight.tournamentId = :tournamentId', {
        tournamentId: options.tournamentId,
      });
    }

    if (options.playerId) {
      queryBuilder.andWhere('highlight.playerId = :playerId', {
        playerId: options.playerId,
      });
    }

    if (options.createdBy) {
      queryBuilder.andWhere('highlight.createdBy = :createdBy', {
        createdBy: options.createdBy,
      });
    }

    if (options.status) {
      queryBuilder.andWhere('highlight.status = :status', { status: options.status });
    }

    if (options.type) {
      queryBuilder.andWhere('highlight.type = :type', { type: options.type });
    }

    if (options.source) {
      queryBuilder.andWhere('highlight.source = :source', { source: options.source });
    }

    if (options.region) {
      queryBuilder.andWhere('highlight.region = :region', { region: options.region });
    }

    // Sorting
    const sortBy = options.sortBy || 'createdAt';
    const sortOrder = options.sortOrder || 'desc';
    queryBuilder.orderBy(`highlight.${sortBy}`, sortOrder.toUpperCase() as 'ASC' | 'DESC');

    // Pagination
    const limit = Math.min(options.limit || 50, 100);
    const offset = options.offset || 0;

    const [highlights, total] = await queryBuilder
      .limit(limit)
      .offset(offset)
      .getManyAndCount();

    return { highlights, total };
  }

  async delete(id: string): Promise<void> {
    const highlight = await this.findById(id);
    if (!highlight) {
      throw new NotFoundError('Highlight', id);
    }

    // Don't allow deletion of highlights being processed
    if (highlight.status === HighlightStatus.PROCESSING) {
      throw new ValidationError('Cannot delete highlight while processing');
    }

    await this.highlightRepo.remove(highlight);

    // Remove from cache
    await this.cacheService.delete(`highlight:${id}`);
  }

  async getHighlightsByStream(streamSessionId: string): Promise<HighlightEntity[]> {
    const cacheKey = `highlights_stream:${streamSessionId}`;
    const cached = await this.cacheService.get<HighlightEntity[]>(cacheKey);
    if (cached) {
      return cached;
    }

    const highlights = await this.highlightRepo.find({
      where: { streamSessionId },
      relations: ['creator'],
      order: { createdAt: 'DESC' },
    });

    // Cache for 5 minutes
    await this.cacheService.set(cacheKey, highlights, 300);

    return highlights;
  }

  async getHighlightsByPlayer(playerId: string): Promise<HighlightEntity[]> {
    const cacheKey = `highlights_player:${playerId}`;
    const cached = await this.cacheService.get<HighlightEntity[]>(cacheKey);
    if (cached) {
      return cached;
    }

    const highlights = await this.highlightRepo.find({
      where: { playerId, status: HighlightStatus.PUBLISHED },
      relations: ['creator', 'streamSession'],
      order: { publishedAt: 'DESC' },
    });

    // Cache for 5 minutes
    await this.cacheService.set(cacheKey, highlights, 300);

    return highlights;
  }

  async getPendingHighlights(): Promise<HighlightEntity[]> {
    const cacheKey = 'pending_highlights';
    const cached = await this.cacheService.get<HighlightEntity[]>(cacheKey);
    if (cached) {
      return cached;
    }

    const highlights = await this.highlightRepo.find({
      where: { status: HighlightStatus.READY },
      relations: ['creator', 'streamSession'],
      order: { createdAt: 'ASC' },
    });

    // Cache for 2 minutes
    await this.cacheService.set(cacheKey, highlights, 120);

    return highlights;
  }

  async getHighlightStats(createdBy?: string): Promise<{
    totalHighlights: number;
    totalViews: number;
    totalLikes: number;
    totalShares: number;
    avgDuration: number;
    publishedHighlights: number;
    pendingHighlights: number;
    rejectedHighlights: number;
  }> {
    const queryBuilder = this.highlightRepo.createQueryBuilder('highlight');
    
    if (createdBy) {
      queryBuilder.where('highlight.createdBy = :createdBy', { createdBy });
    }

    const highlights = await queryBuilder.getMany();

    const totalHighlights = highlights.length;
    const publishedHighlights = highlights.filter(h => h.status === HighlightStatus.PUBLISHED).length;
    const pendingHighlights = highlights.filter(h => h.status === HighlightStatus.READY).length;
    const rejectedHighlights = highlights.filter(h => h.status === HighlightStatus.REJECTED).length;
    
    const totalViews = highlights.reduce(
      (sum, highlight) => sum + highlight.engagement.views,
      0
    );
    
    const totalLikes = highlights.reduce(
      (sum, highlight) => sum + highlight.engagement.likes,
      0
    );
    
    const totalShares = highlights.reduce(
      (sum, highlight) => sum + highlight.engagement.shares,
      0
    );

    const avgDuration = totalHighlights > 0 
      ? highlights.reduce((sum, h) => sum + h.duration, 0) / totalHighlights 
      : 0;

    return {
      totalHighlights,
      totalViews,
      totalLikes,
      totalShares,
      avgDuration,
      publishedHighlights,
      pendingHighlights,
      rejectedHighlights,
    };
  }
}
