import { IsEnum, IsOptional, IsString, IsNumber, IsInt, IsBoolean, IsArray, IsObject, IsDateString, Min, Max, IsUUID } from 'class-validator';
import { Type } from 'class-transformer';
import { HighlightType, HighlightSource, HighlightStatus } from '../database/entities/highlight.entity';

export class CreateHighlightDto {
  @IsUUID()
  streamSessionId!: string;

  @IsOptional()
  @IsUUID()
  matchId?: string;

  @IsOptional()
  @IsUUID()
  tournamentId?: string;

  @IsOptional()
  @IsUUID()
  playerId?: string;

  @IsUUID()
  createdBy!: string;

  @IsEnum(HighlightType)
  type!: HighlightType;

  @IsEnum(HighlightSource)
  source!: HighlightSource;

  @IsString()
  title!: string;

  @IsOptional()
  @IsString()
  description?: string;

  @IsNumber()
  @Min(0)
  startTime!: number;

  @IsNumber()
  @Min(0)
  endTime!: number;

  @IsOptional()
  @IsObject()
  metadata?: {
    platform?: string;
    platformClipId?: string;
    tags?: string[];
    language?: string;
    region?: string;
    featured?: boolean;
    priority?: number;
    autoGenerated?: boolean;
  };

  @IsOptional()
  @IsObject()
  aiMetadata?: {
    confidence: number;
    detectedEvents: Array<{
      event: string;
      timestamp: number;
      confidence: number;
      metadata?: Record<string, any>;
    }>;
    tags: string[];
    sentiment?: 'positive' | 'negative' | 'neutral';
    excitement?: number;
  };

  @IsOptional()
  @IsString()
  region?: string;
}

export class UpdateHighlightDto {
  @IsOptional()
  @IsString()
  title?: string;

  @IsOptional()
  @IsString()
  description?: string;

  @IsOptional()
  @IsObject()
  metadata?: Record<string, any>;

  @IsOptional()
  @IsObject()
  aiMetadata?: Record<string, any>;

  @IsOptional()
  @IsDateString()
  expiresAt?: string;
}

export class HighlightQueryDto {
  @IsOptional()
  @IsUUID()
  streamSessionId?: string;

  @IsOptional()
  @IsUUID()
  matchId?: string;

  @IsOptional()
  @IsUUID()
  tournamentId?: string;

  @IsOptional()
  @IsUUID()
  playerId?: string;

  @IsOptional()
  @IsUUID()
  createdBy?: string;

  @IsOptional()
  @IsEnum(HighlightStatus)
  status?: HighlightStatus;

  @IsOptional()
  @IsEnum(HighlightType)
  type?: HighlightType;

  @IsOptional()
  @IsEnum(HighlightSource)
  source?: HighlightSource;

  @IsOptional()
  @IsString()
  region?: string;

  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(100)
  limit?: number = 50;

  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(0)
  offset?: number = 0;

  @IsOptional()
  @IsEnum(['createdAt', 'duration', 'views', 'likes', 'engagement'])
  sortBy?: 'createdAt' | 'duration' | 'views' | 'likes' | 'engagement' = 'createdAt';

  @IsOptional()
  @IsEnum(['asc', 'desc'])
  sortOrder?: 'asc' | 'desc' = 'desc';
}

export class CompleteHighlightDto {
  @IsUUID()
  highlightId!: string;

  @IsString()
  videoUrl!: string;

  @IsString()
  downloadUrl!: string;

  @IsOptional()
  @IsString()
  thumbnailUrl?: string;

  @IsOptional()
  @IsString()
  embedUrl?: string;

  @IsObject()
  videoMetadata!: {
    format: string;
    resolution: string;
    fps: number;
    bitrate: number;
    fileSize: number;
    codec?: string;
    aspectRatio?: string;
  };
}

export class ApproveHighlightDto {
  @IsUUID()
  highlightId!: string;

  @IsUUID()
  approvedBy!: string;

  @IsOptional()
  @IsDateString()
  approvedAt?: string;
}

export class RejectHighlightDto {
  @IsUUID()
  highlightId!: string;

  @IsUUID()
  approvedBy!: string;

  @IsString()
  rejectionReason!: string;
}

export class PublishHighlightDto {
  @IsUUID()
  highlightId!: string;
}

export class FailHighlightDto {
  @IsUUID()
  highlightId!: string;

  @IsString()
  errorMessage!: string;
}

export class UpdateHighlightEngagementDto {
  @IsUUID()
  highlightId!: string;

  @IsOptional()
  @IsNumber()
  @Min(0)
  views?: number;

  @IsOptional()
  @IsNumber()
  @Min(0)
  likes?: number;

  @IsOptional()
  @IsNumber()
  @Min(0)
  shares?: number;

  @IsOptional()
  @IsNumber()
  @Min(0)
  downloads?: number;

  @IsOptional()
  @IsNumber()
  @Min(0)
  comments?: number;

  @IsOptional()
  @IsNumber()
  @Min(0)
  watchTime?: number;
}

export class HighlightStatsDto {
  @IsOptional()
  @IsUUID()
  createdBy?: string;
}
