import {
  Entity,
  Index,
  Column,
  ManyToOne,
  JoinColumn,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
} from 'typeorm';
import { StreamSessionEntity } from './stream-session.entity';
import { MatchEntity } from './match.entity';
import { UserEntity } from './user.entity';
import { TournamentEntity } from './tournament.entity';

export enum HighlightStatus {
  PROCESSING = 'processing',
  READY = 'ready',
  APPROVED = 'approved',
  REJECTED = 'rejected',
  PUBLISHED = 'published',
  FAILED = 'failed',
}

export enum HighlightType {
  KILL = 'kill',
  DEATH = 'death',
  WIN = 'win',
  CLUTCH = 'clutch',
  ACE = 'ace',
  MULTIKILL = 'multikill',
  ROUND_WIN = 'round_win',
  ROUND_LOSS = 'round_loss',
  MATCH_WIN = 'match_win',
  MATCH_LOSS = 'match_loss',
  CUSTOM = 'custom',
}

export enum HighlightSource {
  AUTO_GENERATED = 'auto_generated',
  MANUAL_CREATED = 'manual_created',
  AI_DETECTED = 'ai_detected',
  USER_SUBMITTED = 'user_submitted',
}

@Entity('highlights')
@Index(['streamSessionId'])
@Index(['matchId'])
@Index(['tournamentId'])
@Index(['playerId'])
@Index(['status'])
@Index(['type'])
@Index(['source'])
@Index(['createdAt'])
export class HighlightEntity {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ type: 'uuid' })
  streamSessionId!: string;

  @ManyToOne(() => StreamSessionEntity, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'streamSessionId' })
  streamSession!: StreamSessionEntity;

  @Column({ type: 'uuid', nullable: true })
  matchId!: string;

  @ManyToOne(() => MatchEntity, { nullable: true, onDelete: 'CASCADE' })
  @JoinColumn({ name: 'matchId' })
  match?: MatchEntity;

  @Column({ type: 'uuid', nullable: true })
  tournamentId!: string;

  @ManyToOne(() => TournamentEntity, { nullable: true, onDelete: 'CASCADE' })
  @JoinColumn({ name: 'tournamentId' })
  tournament?: TournamentEntity;

  @Column({ type: 'uuid', nullable: true })
  playerId!: string;

  @ManyToOne(() => UserEntity, { nullable: true, onDelete: 'CASCADE' })
  @JoinColumn({ name: 'playerId' })
  player?: UserEntity;

  @Column({ type: 'uuid', nullable: true })
  createdBy!: string;

  @ManyToOne(() => UserEntity, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'createdBy' })
  creator!: UserEntity;

  @Column({
    type: 'enum',
    enum: HighlightStatus,
    default: HighlightStatus.PROCESSING,
  })
  status!: HighlightStatus;

  @Column({
    type: 'enum',
    enum: HighlightType,
  })
  type!: HighlightType;

  @Column({
    type: 'enum',
    enum: HighlightSource,
    default: HighlightSource.AUTO_GENERATED,
  })
  source!: HighlightSource;

  @Column({ type: 'varchar', length: 255 })
  title!: string;

  @Column({ type: 'text', nullable: true })
  description?: string;

  @Column({ type: 'int' })
  startTime!: number; // seconds from stream start

  @Column({ type: 'int' })
  endTime!: number; // seconds from stream start

  @Column({ type: 'int' })
  duration!: number; // in seconds

  @Column({ type: 'varchar', length: 255, nullable: true })
  thumbnailUrl?: string;

  @Column({ type: 'varchar', length: 255, nullable: true })
  videoUrl?: string;

  @Column({ type: 'varchar', length: 255, nullable: true })
  downloadUrl?: string;

  @Column({ type: 'varchar', length: 255, nullable: true })
  embedUrl?: string;

  @Column({ type: 'jsonb', default: {} })
  videoMetadata!: {
    format: string;
    resolution: string;
    fps: number;
    bitrate: number;
    fileSize: number;
    codec?: string;
    aspectRatio?: string;
  };

  @Column({ type: 'jsonb', default: {} })
  processingMetadata!: {
    processingStartedAt?: Date;
    processingCompletedAt?: Date;
    processingDuration?: number;
    processingSteps: Array<{
      step: string;
      startedAt: Date;
      completedAt?: Date;
      status: 'pending' | 'processing' | 'completed' | 'failed';
      error?: string;
    }>;
    retryCount: number;
    lastRetryAt?: Date;
  };

  @Column({ type: 'jsonb', default: {} })
  aiMetadata!: {
    confidence: number;
    detectedEvents: Array<{
      event: string;
      timestamp: number;
      confidence: number;
      metadata?: Record<string, any>;
    }>;
    tags: string[];
    sentiment?: 'positive' | 'negative' | 'neutral';
    excitement?: number; // 0-1 scale
  };

  @Column({ type: 'jsonb', default: {} })
  engagement!: {
    views: number;
    likes: number;
    shares: number;
    downloads: number;
    comments: number;
    watchTime: number; // total watch time in seconds
  };

  @Column({ type: 'jsonb', default: {} })
  metadata!: {
    platform: string;
    platformClipId?: string;
    tags: string[];
    language?: string;
    region?: string;
    featured: boolean;
    priority: number;
    autoGenerated: boolean;
  };

  @Column({ type: 'text', nullable: true })
  rejectionReason?: string;

  @Column({ type: 'uuid', nullable: true })
  approvedBy?: string;

  @ManyToOne(() => UserEntity, { nullable: true })
  @JoinColumn({ name: 'approvedBy' })
  approver?: UserEntity;

  @Column({ type: 'timestamptz', nullable: true })
  approvedAt?: Date;

  @Column({ type: 'timestamptz', nullable: true })
  publishedAt?: Date;

  @Column({ type: 'timestamptz', nullable: true })
  expiresAt?: Date;

  @Column({ type: 'varchar', length: 50, default: 'global' })
  region!: string;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt!: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt!: Date;
}
