import type { GlobalConfig } from "../types/globalConfig";

const matchDisputeWindowMinutes = Number(process.env.MATCH_DISPUTE_WINDOW_MINUTES ?? 30);
const matchConcurrencyLockStrategy = (process.env.MATCH_CONCURRENCY_LOCK ?? "db") as "db" | "redis";

const globalConfig: GlobalConfig = {
  metadata: {
    appName: "RBx",
    organization: "THE MACRO EXECUTIVE",
    developerCredits: "RAWR, _____",
    version: "1.0.0",
    supportEmail: "support@rbx.gg",
    marketingSite: "https://rbx.gg",
  },
  featureFlags: {
    enableBRMode: true,
    enableCSMode: true,
    enableVersusMode: true,
    enableInvitedTeams: true,
    enableFreeTournamentCreationFees: true,
    enableKycGate: true,
    enableAutoRoomDistribution: true,
    enableDisputeReEntry: true,
    enablePaymentWebhooks: true,
  },
  organizer: {
    creationFees: {
      small: 50,
      medium: 200,
      large: 500,
    },
    tournamentTypeChangeFee: 10,
    defaultFreeReshuffles: 3,
    extraReshuffleFee: 2,
    maxTournamentsPerDay: 5,
    cooldownHoursAfterBan: 72,
    invitedSlotLimit: 5,
    maxConcurrentDrafts: 3,
    kycRequiredAboveAmount: 5000,
    fraudStrikeThreshold: 3,
    manualApprovalRequired: true,
  },
  tournament: {
    platformCut: 0.01,
    registrationWindowHours: 72,
    refundWindowHours: 24,
    defaultMatchDurationMinutes: 20,
    defaultBufferMinutes: 10,
    maxMatchesPerDay: 10,
    autoRoomReminderMinutes: 15,
    maxQualifierRounds: 4,
    invitedTeamBypassRounds: true,
    minimumTeamSize: 4,
    maximumTeamSize: 6,
    br: {
      teamsPerMatch: 13,
      reshuffleLimit: 5,
      selectionStrategy: "random",
      allowManualOverrides: true,
    },
    cs: {
      concurrentMatches: 6,
      matchDurationMinutes: 12,
      defaultBestOf: 3,
      forfeitGracePeriodMinutes: 5,
    },
    refunds: {
      allowCreationFeeRefundBeforeRegistration: true,
      allowRegistrationRefundBeforeSchedule: true,
      maxRefundAttempts: 1,
      gatewayFeeRefundable: false,
    },
    invitedSlots: {
      allowOrganizerInvites: true,
      maxInvitedTeamsPerTournament: 20,
      inviteCodePrefix: "RBX-INV-",
    },
    text: {
      registrationClosed: "Registrations have closed for this tournament.",
      registrationSuccess: "You are successfully registered for the tournament!",
      schedulePending: "Match schedule will be announced soon.",
      roomDetailsPending: "Room ID & password will be shared before match start.",
      organizerFeePending: "Organizer must complete the creation fee payment before publishing.",
    },
  },
  versus: {
    platformCut: 0.1,
    minimumStake: 10,
    maximumStake: 10000,
    roomCodeTemplate: "Versus Room ID: {{roomId}}, Pass: {{password}}",
    defaultMatchTimeoutMinutes: 15,
    allowedModes: ["CS", "BR"],
    allowAutoForfeitDetection: true,
    disputeWindowMinutes: 30,
  },
  payments: {
    primaryGateway: "razorpay",
    backupGateway: "paytm", 
    payoutGateway: "razorpayx",
    sandboxMode: true,
    minimumBalanceForPayout: 200,
    maximumPayoutPerDay: 100000,
    escrowHoldHours: 48,
    settlementBufferHours: 6,
    platformFeePercent: 1,
    versusPlatformFeePercent: 10,
    escrowEnabled: true,
    payoutMinAmountCents: 100,
    gateways: {
      paytm: {
        enabled: true,
        testMode: true,
        merchantIdEnv: "PAYTM_MERCHANT_ID",
        merchantKeyEnv: "PAYTM_MERCHANT_KEY",
        webhookSecretEnv: "PAYTM_WEBHOOK_SECRET",
      },
      razorpay: {
        enabled: true,
        testMode: true,
        webhookSecretEnv: "RAZORPAY_WEBHOOK_SECRET",
        apiKeyEnv: "RAZORPAY_KEY_ID",
        apiSecretEnv: "RAZORPAY_KEY_SECRET",
      },
      paypal: {
        enabled: false,
        testMode: true,
        webhookSecretEnv: "PAYPAL_WEBHOOK_SECRET",
        clientIdEnv: "PAYPAL_CLIENT_ID",
        clientSecretEnv: "PAYPAL_CLIENT_SECRET",
      },
    },
    razorpayX: {
      apiKeyEnv: "RAZORPAYX_KEY_ID",
      apiSecretEnv: "RAZORPAYX_KEY_SECRET",
      accountNumberEnv: "RAZORPAYX_ACCOUNT_NUMBER",
    },
    refundPolicy: {
      allowManualReview: true,
      automaticApprovalBelowAmount: 200,
      disputeResolutionTimeHours: 24,
      notifyFinanceEmail: "finance@rbx.gg",
    },
  },
  notifications: {
    morningReminderTime: "09:00",
    thirtyMinReminderTime: "-00:30",
    fiveMinReminderTime: "-00:05",
    templates: {
      registrationClosed: "Registration closed for {{tournamentName}}.",
      matchSelected: "Your team {{teamName}} has been selected for {{tournamentName}}.",
      matchScheduled: "Match {{matchCode}} scheduled on {{matchDate}} at {{matchTime}}.",
      dayOfReminder: "Reminder: Match {{matchCode}} starts today.",
      thirtyMinReminder: "30 minutes to match {{matchCode}}. Join the room soon!",
      fiveMinReminder: "5 minutes to match {{matchCode}}. Be ready!",
      matchStart: "Match {{matchCode}} has started.",
      matchEnd: "Match {{matchCode}} has ended. Submit proofs.",
      resultPublished: "Results for {{matchCode}} are live.",
      disputeUpdate: "Dispute {{disputeId}} updated: {{status}}.",
      versusRoom: "Versus room ready: {{roomDetails}}",
      organizerFeePending: "Complete your organizer creation fee to publish {{tournamentName}}.",
    },
    pushChannels: ["fcm", "inApp", "sms"],
    emailSender: "no-reply@rbx.gg",
    smsSenderName: "RBXGG",
  },
  scheduling: {
    lockTtlSeconds: 120,
    defaultTimezone: "Asia/Kolkata",
    autoScheduleRetries: 3,
    autoScheduleRetryDelaySeconds: 30,
    redisKeys: {
      tournamentLockPrefix: "rbx:tournament:lock:",
      matchLockPrefix: "rbx:match:lock:",
    },
    reshuffle: {
      requireReason: true,
      auditLogEnabled: true,
    },
    workers: {
      schedulerQueue: "rbx:scheduler",
      notificationQueue: "rbx:notifications",
      paymentQueue: "rbx:payments",
    },
  },
  match: {
    disputeWindowMinutes: matchDisputeWindowMinutes,
    concurrencyLockStrategy: matchConcurrencyLockStrategy,
  },
  limits: {
    maxTeamsPerTournament: 1024,
    maxPlayersPerTeam: 6,
    minPlayersPerTeam: 4,
    maxOrganizers: 1000,
    maxDisputesPerTeam: 2,
    maxProofUploadsPerMatch: 5,
    maxWaitlistSize: 200,
    maxVersusPerDay: 10,
  },
  security: {
    jwtExpiryMinutes: 60,
    jwtRefreshDays: 30,
    rateLimiterWindowSeconds: 60,
    rateLimiterMaxRequests: 30,
    ipReputationThreshold: 75,
    maxFailedPaymentAttempts: 3,
    webhookToleranceMinutes: 5,
    enforceDeviceBinding: true,
    enableIpLogging: true,
  },
  textContent: {
    welcomeBanner: "Welcome to RBx — Battle smarter, win bigger.",
    organizerInstructions: "Complete KYC and pay creation fees to publish tournaments.",
    versusDisclaimer: "Winnings are credited post verification. Cheating leads to bans.",
    disputeGuidelines: "Submit video or screenshot proof within the dispute window.",
    paymentInfo: "All payments are processed via secure gateways.",
    maintenanceMessage: "RBx services may be unavailable during scheduled maintenance windows.",
  },
  storage: {
    mediaCdnBaseUrl: "https://cdn.rbx.gg",
    s3BucketEnv: "RBX_S3_BUCKET",
    proofRetentionDays: 30,
    roomDetailTtlMinutes: 60,
    cdnCacheSeconds: 300,
  },
  support: {
    faqUrl: "https://rbx.gg/faq",
    discordInvite: "https://discord.gg/rbx",
    escalationEmail: "ce@rbx.gg",
    officeHours: "Mon-Sat 10:00-19:00 IST",
  },
};

export default globalConfig;
